image:
  tag: 4.4.4-debian-10-r5
auth:
  existingSecret: bookinfo-prd-ratings-mongodb-secret
  username: ratings-prd
  database: ratings-prd
persistence:
  enabled: false
initdbScriptsConfigMap: bookinfo-prd-ratings-mongodb-initdb
